@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Sep 23 11:10:27 +0700 2025
=======
REM Generated by Vivado on Mon Sep 22 09:32:19 +0700 2025
>>>>>>> ec0693c425aca3de38c4f220525b428dc2e94a0b
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
echo "xvlog --incr --relax -prj multifunction_barrel_shifter_tb_vlog.prj"
call xvlog  --incr --relax -prj multifunction_barrel_shifter_tb_vlog.prj -log xvlog.log
=======
echo "xvlog --incr --relax -prj barrel_shifter_tb_vlog.prj"
call xvlog  --incr --relax -prj barrel_shifter_tb_vlog.prj -log xvlog.log
>>>>>>> ec0693c425aca3de38c4f220525b428dc2e94a0b
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
