@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Sep 23 10:51:15 +0700 2025
=======
REM Generated by Vivado on Mon Sep 22 09:30:08 +0700 2025
>>>>>>> ec0693c425aca3de38c4f220525b428dc2e94a0b
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
echo "xsim multifunction_barrel_shifter_tb_behav -key {Behavioral:sim_1:Functional:multifunction_barrel_shifter_tb} -tclbatch multifunction_barrel_shifter_tb.tcl -log simulate.log"
call xsim  multifunction_barrel_shifter_tb_behav -key {Behavioral:sim_1:Functional:multifunction_barrel_shifter_tb} -tclbatch multifunction_barrel_shifter_tb.tcl -log simulate.log
=======
echo "xsim barrel_shifter_tb_behav -key {Behavioral:sim_1:Functional:barrel_shifter_tb} -tclbatch barrel_shifter_tb.tcl -log simulate.log"
call xsim  barrel_shifter_tb_behav -key {Behavioral:sim_1:Functional:barrel_shifter_tb} -tclbatch barrel_shifter_tb.tcl -log simulate.log
>>>>>>> ec0693c425aca3de38c4f220525b428dc2e94a0b
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
