@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD
REM Generated by Vivado on Fri Aug 29 13:42:34 +0700 2025
=======
REM Generated by Vivado on Fri Aug 29 10:05:53 +0700 2025
>>>>>>> b3d6db3dcece7f9e6a14ad4bc4e1f516e837604d
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
echo "xvlog --incr --relax -prj tb_comp_2bit_vlog.prj"
call xvlog  --incr --relax -prj tb_comp_2bit_vlog.prj -log xvlog.log
=======
echo "xvlog --incr --relax -prj tb_greater_2bit_vlog.prj"
call xvlog  --incr --relax -prj tb_greater_2bit_vlog.prj -log xvlog.log
>>>>>>> b3d6db3dcece7f9e6a14ad4bc4e1f516e837604d
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
