@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
<<<<<<< HEAD
REM Generated by Vivado on Thu Aug 28 20:15:21 +0700 2025
=======
REM Generated by Vivado on Fri Aug 29 10:05:54 +0700 2025
>>>>>>> b3d6db3dcece7f9e6a14ad4bc4e1f516e837604d
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
echo "xelab -wto 6184bb1d0d4d46999bd3d57d3a043caa --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_comp_2bit_behav xil_defaultlib.tb_comp_2bit xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 6184bb1d0d4d46999bd3d57d3a043caa --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_comp_2bit_behav xil_defaultlib.tb_comp_2bit xil_defaultlib.glbl -log elaborate.log
=======
echo "xelab -wto 6184bb1d0d4d46999bd3d57d3a043caa --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_greater_2bit_behav xil_defaultlib.tb_greater_2bit xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 6184bb1d0d4d46999bd3d57d3a043caa --incr --debug typical --relax --mt 2 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot tb_greater_2bit_behav xil_defaultlib.tb_greater_2bit xil_defaultlib.glbl -log elaborate.log
>>>>>>> b3d6db3dcece7f9e6a14ad4bc4e1f516e837604d
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
